import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from "sonner";
import { Inter } from "next/font/google";


import { ThemeProvider } from '@/components/theme-provider';


const inter = Inter({subsets: ['latin']})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Vidlif | Real Time Data Sharing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}>
        
        
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey="vidlif-theme"
          >
            {children}
            <Toaster theme='light' position='bottom-center' />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
};
 